//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialResoucres
    {
        public int Id { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> CostType { get; set; }
    
        public virtual CostTypes CostTypes { get; set; }
        public virtual Resources Resources { get; set; }
    }
}
