//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.Models
{
    using ProjectManager.Models.Repositories;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class Projects : IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projects()
        {
            this.ProjectResources = new HashSet<ProjectResources>();
            this.ProjectTasks = new HashSet<ProjectTasks>();
            this.Users = new HashSet<Users>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreatingDate { get; set; }
        public Nullable<int> User { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectResources> ProjectResources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTasks> ProjectTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }

        [NotMapped]
        public ICollection<Tasks> ProjectRootTasks
        {
            get
            {
                return new Repository<ProjectTasks>().Items
                .Select(item => item.Tasks)
                .Join(new Repository<TaskGroups>().Items, projectTask => projectTask.Id, taskGroup => taskGroup.Id, (projectTask, taskGroup) => taskGroup)
                .Where(item => item.Depth == 1)
                .Select(item => item.Tasks)
                .Distinct().ToList();
            }
        }

    }
}
