//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTaskResources : IEntity
    {
        public int Id { get; set; }
        public Nullable<int> ProjectTask { get; set; }
        public Nullable<int> ProjectResource { get; set; }
    
        public virtual ProjectResources ProjectResources { get; set; }
        public virtual ProjectTasks ProjectTasks { get; set; }
    }
}
