//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectManagerDb : DbContext
    {
        public ProjectManagerDb()
            : base("name=ProjectManagerDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CostTypes> CostTypes { get; set; }
        public virtual DbSet<DateTypes> DateTypes { get; set; }
        public virtual DbSet<MaterialResoucres> MaterialResoucres { get; set; }
        public virtual DbSet<Permissions> Permissions { get; set; }
        public virtual DbSet<Persons> Persons { get; set; }
        public virtual DbSet<ProjectResources> ProjectResources { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<ProjectTasks> ProjectTasks { get; set; }
        public virtual DbSet<Resources> Resources { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SalaryTypes> SalaryTypes { get; set; }
        public virtual DbSet<TaskConnections> TaskConnections { get; set; }
        public virtual DbSet<TaskGroups> TaskGroups { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
        public virtual DbSet<TaskTypes> TaskTypes { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WeekDays> WeekDays { get; set; }
        public virtual DbSet<WorkingCalendars> WorkingCalendars { get; set; }
        public virtual DbSet<WorkingCalendarWeekends> WorkingCalendarWeekends { get; set; }
        public virtual DbSet<WorkingResources> WorkingResources { get; set; }
    }
}
