//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskGroups
    {
        public int Id { get; set; }
        public int Parent { get; set; }
        public int Child { get; set; }
        public int Depth { get; set; }
    
        public virtual Tasks Tasks { get; set; }
        public virtual Tasks Tasks1 { get; set; }
    }
}
